CREATE TABLE FABRICANTE (
  ID_FABRICANTE INT NOT NULL AUTO_INCREMENT,
  CNPJ VARCHAR(20) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(150),
  PRIMARY KEY (ID_FABRICANTE)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PRODUTO (
  ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  TIPO_EMBALAGEM VARCHAR(50) NOT NULL,
  QUANTIDADE DECIMAL(10,2) UNSIGNED NOT NULL,
  TIPO_PRODUTO ENUM('Medicamento', 'Perfumaria') NOT NULL,
  ID_FABRICANTE INT NOT NULL,
  PRIMARY KEY (ID_PRODUTO),
  FOREIGN KEY (ID_FABRICANTE) REFERENCES FABRICANTE(ID_FABRICANTE)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MEDICAMENTO (
  ID_MEDICAMENTO INT NOT NULL AUTO_INCREMENT,
  TARJA VARCHAR(20) NOT NULL,
  FORMULA VARCHAR(100) NOT NULL,
  ID_PRODUTO INT NOT NULL,
  PRIMARY KEY (ID_MEDICAMENTO),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PERFUMARIA (
  ID_PERFUMARIA INT NOT NULL AUTO_INCREMENT,
  TIPO VARCHAR(100) NOT NULL,
  ID_PRODUTO INT NOT NULL,
  PRIMARY KEY (ID_PERFUMARIA),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE VENDA (
  ID_VENDA INT NOT NULL AUTO_INCREMENT,
  NUMERO VARCHAR(20) NOT NULL,
  DATA DATE NOT NULL,
  CLIENTE VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_VENDA)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE RECEITA_MEDICA (
  ID_RECEITA_MEDICA INT NOT NULL AUTO_INCREMENT,
  CRM_MEDICO VARCHAR(20) NOT NULL,
  NOME_MEDICO VARCHAR(100) NOT NULL,
  NOME_PACIENTE VARCHAR(100) NOT NULL,
  DATA_RECEITA DATE NOT NULL,
  OBSERVACAO VARCHAR(200) NOT NULL,
  PRIMARY KEY (ID_RECEITA_MEDICA)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE VENDA_MEDICAMENTO (
  ID_VENDA_MEDICAMENTO INT NOT NULL AUTO_INCREMENT,
  ID_VENDA INT NOT NULL,
  QUANTIDADE INT NOT NULL,
  DOSAGEM VARCHAR(50) NOT NULL,
  ID_MEDICAMENTO INT NOT NULL,
  ID_RECEITA_MEDICA INT NOT NULL,
  PRIMARY KEY (ID_VENDA_MEDICAMENTO),
  FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID_VENDA)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_RECEITA_MEDICA) REFERENCES RECEITA_MEDICA(ID_RECEITA_MEDICA)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE VENDA_PERFUMARIA (
  ID_VENDA_PERFUMARIA INT NOT NULL AUTO_INCREMENT,
  QUANTIDADE INT NOT NULL,
  ID_VENDA INT NOT NULL,
  ID_PERFUMARIA INT NOT NULL,
  PRIMARY KEY (ID_VENDA_PERFUMARIA),
  FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID_VENDA)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_PERFUMARIA) REFERENCES PERFUMARIA(ID_PERFUMARIA)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO FABRICANTE (CNPJ, NOME, ENDERECO)
VALUES ('12.345.678/0001-99', 'Farmacêutica Vida', 'Rua das Flores, 123');

INSERT INTO PRODUTO (NOME, TIPO_EMBALAGEM, QUANTIDADE, TIPO_PRODUTO, ID_FABRICANTE)
VALUES ('Paracetamol 500mg', 'Caixa', 20.00, 'Medicamento', 1),
       ('Colônia Floral', 'Frasco', 15.00, 'Perfumaria', 1);
       
INSERT INTO MEDICAMENTO (TARJA, FORMULA, ID_PRODUTO)
VALUES ('Vermelha', 'Paracetamol + Cafeína', 1);

INSERT INTO PERFUMARIA (TIPO, ID_PRODUTO)
VALUES ('Colônia', 2);

INSERT INTO VENDA (NUMERO, DATA, CLIENTE)
VALUES ('VENDA001', '2025-11-04', 'João da Silva');

INSERT INTO RECEITA_MEDICA (CRM_MEDICO, NOME_MEDICO, NOME_PACIENTE, DATA_RECEITA, OBSERVACAO)
VALUES ('123456-SP', 'Dra. Ana Costa', 'João da Silva', '2025-11-04', 'Tomar 1 comprimido após o almoço');

INSERT INTO VENDA_MEDICAMENTO (ID_VENDA, QUANTIDADE, DOSAGEM, ID_MEDICAMENTO, ID_RECEITA_MEDICA)
VALUES (1, 2, '500mg', 1, 1);

INSERT INTO VENDA_PERFUMARIA (QUANTIDADE, ID_VENDA, ID_PERFUMARIA)
VALUES (1, 1, 1);

SELECT V.NUMERO, V.DATA, V.CLIENTE, M.FORMULA, VM.DOSAGEM
FROM VENDA_MEDICAMENTO VM
JOIN VENDA V ON VM.ID_VENDA = V.ID_VENDA
JOIN MEDICAMENTO M ON VM.ID_MEDICAMENTO = M.ID_MEDICAMENTO;

DELETE FROM VENDA_MEDICAMENTO
WHERE ID_VENDA_MEDICAMENTO = 2;