CREATE DATABASE IF NOT EXISTS locadora;
USE locadora;

-- Tabela genérica: tipo de veículo
CREATE TABLE TIPO_VEICULO (
  ID_TIPO_VEICULO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  MARCA VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_TIPO_VEICULO)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de veículos (instância)
CREATE TABLE VEICULO (
  ID_VEICULO INT NOT NULL AUTO_INCREMENT,
  NUMERO_VEICULO INT NOT NULL,
  PLACA VARCHAR(10) NOT NULL,
  DATA_PROXIMA_MANUTENCAO DATE NOT NULL,
  ID_TIPO_VEICULO INT NOT NULL,
  PRIMARY KEY (ID_VEICULO),
  UNIQUE (NUMERO_VEICULO),
  UNIQUE (PLACA),
  FOREIGN KEY (ID_TIPO_VEICULO) REFERENCES TIPO_VEICULO(ID_TIPO_VEICULO)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- Especialização: Automóvel
CREATE TABLE AUTOMOVEL (
  ID_TIPO_VEICULO INT NOT NULL,
  NUMERO_PORTAS INT NOT NULL,
  DIRACAO_HIDRAULICA TINYINT NOT NULL,
  CAMBIO_AUTOMATICO TINYINT NOT NULL,
  RADIO TINYINT NOT NULL,
  PRIMARY KEY (ID_TIPO_VEICULO),
  FOREIGN KEY (ID_TIPO_VEICULO) REFERENCES TIPO_VEICULO(ID_TIPO_VEICULO)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- Especialização: Ônibus
CREATE TABLE ONIBUS (
  ID_TIPO_VEICULO INT NOT NULL,
  NUMERO_PASSAGEIRO INT NOT NULL,
  LEITO TINYINT NOT NULL,
  SANITARIO TINYINT NOT NULL,
  PRIMARY KEY (ID_TIPO_VEICULO),
  FOREIGN KEY (ID_TIPO_VEICULO) REFERENCES TIPO_VEICULO(ID_TIPO_VEICULO)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- Escritório
CREATE TABLE ESCRITORIO (
  ID_ESCRITORIO INT NOT NULL AUTO_INCREMENT,
  ENDERECO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_ESCRITORIO)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- Cliente
CREATE TABLE CLIENTE (
  ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
  NUMERO_CARTEIRA_MOTORISTA INT NOT NULL,
  ESTADO_CARTEIRA_MOTORISTA VARCHAR(2) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(150) NOT NULL,
  TELEFONE VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_CLIENTE)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- Contrato de aluguel
CREATE TABLE CONTRATO_DE_ALUGUEL (
  ID_CONTRATO INT NOT NULL AUTO_INCREMENT,
  DATA_INICIO DATE NOT NULL,
  DATA_FIM DATE NOT NULL,
  ID_ESCRITORIO INT NOT NULL,
  ID_VEICULO INT NOT NULL,
  ID_CLIENTE INT NOT NULL,
  PRIMARY KEY (ID_CONTRATO),
  FOREIGN KEY (ID_ESCRITORIO) REFERENCES ESCRITORIO(ID_ESCRITORIO)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(ID_VEICULO)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4; 

-- Tipos de veículo
INSERT INTO TIPO_VEICULO (NOME, MARCA)
VALUES ('Sedan', 'Toyota'),
       ('Ônibus Executivo', 'Mercedes-Benz');

-- Especializações
INSERT INTO AUTOMOVEL (ID_TIPO_VEICULO, NUMERO_PORTAS, DIRACAO_HIDRAULICA, CAMBIO_AUTOMATICO, RADIO)
VALUES (1, 4, 1, 1, 1);

INSERT INTO ONIBUS (ID_TIPO_VEICULO, NUMERO_PASSAGEIRO, LEITO, SANITARIO)
VALUES (2, 42, 1, 1);

-- Veículos
INSERT INTO VEICULO (NUMERO_VEICULO, PLACA, DATA_PROXIMA_MANUTENCAO, ID_TIPO_VEICULO)
VALUES (1001, 'ABC1A23', '2025-12-15', 1),
       (2001, 'XYZ9Z99', '2025-12-20', 2);

-- Escritórios
INSERT INTO ESCRITORIO (ENDERECO)
VALUES ('Av. Brasil, 1000'),
       ('Rua Central, 200');

-- Clientes
INSERT INTO CLIENTE (NUMERO_CARTEIRA_MOTORISTA, ESTADO_CARTEIRA_MOTORISTA, NOME, ENDERECO, TELEFONE)
VALUES (123456789, 'SP', 'Carlos Andrade', 'Rua das Palmeiras, 45', '(16) 99999-1234'),
       (987654321, 'MG', 'Fernanda Lima', 'Av. das Rosas, 88', '(16) 98888-4321');

-- Contratos de aluguel
INSERT INTO CONTRATO_DE_ALUGUEL (DATA_INICIO, DATA_FIM, ID_ESCRITORIO, ID_VEICULO, ID_CLIENTE)
VALUES ('2025-11-01', '2025-11-10', 1, 1, 1),
       ('2025-11-05', '2025-11-15', 2, 2, 2);  
       
       SELECT C.ID_CONTRATO, C.DATA_INICIO, C.DATA_FIM, CL.NOME AS CLIENTE, V.PLACA, TV.NOME AS TIPO
FROM CONTRATO_DE_ALUGUEL C
JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID_CLIENTE
JOIN VEICULO V ON C.ID_VEICULO = V.ID_VEICULO
JOIN TIPO_VEICULO TV ON V.ID_TIPO_VEICULO = TV.ID_TIPO_VEICULO; 