-- CRIAÇÃO DO BANCO
DROP DATABASE IF EXISTS mydb;
CREATE DATABASE mydb;
USE mydb;

-- TIPO_PRODUTO
CREATE TABLE TIPO_PRODUTO (
  ID_TIPO_PRODUTO INT NOT NULL AUTO_INCREMENT,
  DESCRICAO_TIPO_PRODUTO VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_TIPO_PRODUTO)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- PRODUTO
CREATE TABLE PRODUTO (
  ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
  DESCRICAO_PRODUTO VARCHAR(100) NOT NULL,
  PRECO_PRODUTO DECIMAL(10,2) UNSIGNED NOT NULL,
  TIPO_PRODUTO_ID_TIPO_PRODUTO INT NOT NULL,
  PRIMARY KEY (ID_PRODUTO),
  FOREIGN KEY (TIPO_PRODUTO_ID_TIPO_PRODUTO)
    REFERENCES TIPO_PRODUTO(ID_TIPO_PRODUTO)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- REGISTRADORA
CREATE TABLE REGISTRADORA (
  ID_REGISTRADORA INT NOT NULL AUTO_INCREMENT,
  SALDO_REGISTRADO DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (ID_REGISTRADORA)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- EMPREGADO
CREATE TABLE EMPREGADO (
  ID_EMPREGADO INT NOT NULL AUTO_INCREMENT,
  NOME_EMPREGADO VARCHAR(100) NOT NULL,
  SENHA_EMPREGADO BINARY(64) NOT NULL,
  PRIMARY KEY (ID_EMPREGADO)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- VENDA
CREATE TABLE VENDA (
  ID_VENDA INT NOT NULL AUTO_INCREMENT,
  DATA_VENDA DATE NOT NULL,
  ID_EMPREGADO INT NOT NULL,
  ID_REGISTRADORA INT NOT NULL,
  PRIMARY KEY (ID_VENDA),
  FOREIGN KEY (ID_REGISTRADORA) REFERENCES REGISTRADORA(ID_REGISTRADORA)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_EMPREGADO) REFERENCES EMPREGADO(ID_EMPREGADO)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- ITEM_VENDA
CREATE TABLE ITEM_VENDA (
  ID_ITEM_VENDA INT NOT NULL AUTO_INCREMENT,
  ID_PRODUTO INT NOT NULL,
  QUANTIDADE_INTEM INT UNSIGNED NOT NULL,
  PRECO_ITEM DECIMAL(10,2) UNSIGNED NOT NULL,
  ID_VENDA INT NOT NULL,
  PRIMARY KEY (ID_ITEM_VENDA),
  FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID_VENDA)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- SIMILAR
CREATE TABLE SIMILAR (
  ID_PRODUTO_A INT NOT NULL,
  ID_PRODUTO_B INT NOT NULL,
  PRIMARY KEY (ID_PRODUTO_A, ID_PRODUTO_B),
  FOREIGN KEY (ID_PRODUTO_A) REFERENCES PRODUTO(ID_PRODUTO)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_PRODUTO_B) REFERENCES PRODUTO(ID_PRODUTO)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- PRODUTO_has_SIMILAR
CREATE TABLE PRODUTO_has_SIMILAR (
  PRODUTO_ID_PRODUTO INT NOT NULL,
  SIMILAR_ID_PRODUTO_A INT NOT NULL,
  SIMILAR_ID_PRODUTO_B INT NOT NULL,
  PRIMARY KEY (PRODUTO_ID_PRODUTO, SIMILAR_ID_PRODUTO_A, SIMILAR_ID_PRODUTO_B),
  FOREIGN KEY (PRODUTO_ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (SIMILAR_ID_PRODUTO_A, SIMILAR_ID_PRODUTO_B)
    REFERENCES SIMILAR(ID_PRODUTO_A, ID_PRODUTO_B)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- INSERÇÃO DE DADOS
INSERT INTO TIPO_PRODUTO (DESCRICAO_TIPO_PRODUTO) VALUES
('Eletrônico'), ('Vestuário'), ('Alimento');

INSERT INTO PRODUTO (DESCRICAO_PRODUTO, PRECO_PRODUTO, TIPO_PRODUTO_ID_TIPO_PRODUTO) VALUES
('Smartphone Galaxy S21', 3500.00, 1),
('Notebook Dell i5', 4500.00, 1),
('Camiseta Polo', 89.90, 2),
('Calça Jeans', 129.90, 2),
('Chocolate 70% Cacau', 12.50, 3);

INSERT INTO SIMILAR (ID_PRODUTO_A, ID_PRODUTO_B) VALUES
(1, 2), (3, 4), (4, 3);

INSERT INTO PRODUTO_has_SIMILAR (PRODUTO_ID_PRODUTO, SIMILAR_ID_PRODUTO_A, SIMILAR_ID_PRODUTO_B) VALUES
(1, 1, 2), (3, 3, 4), (4, 4, 3);

INSERT INTO EMPREGADO (NOME_EMPREGADO, SENHA_EMPREGADO) VALUES
('Carlos Silva', UNHEX(SHA2('senha123', 256))),
('Fernanda Lima', UNHEX(SHA2('segredo456', 256)));

INSERT INTO REGISTRADORA (SALDO_REGISTRADO) VALUES
(1000.00), (500.00);

INSERT INTO VENDA (DATA_VENDA, ID_EMPREGADO, ID_REGISTRADORA) VALUES
('2025-11-01', 1, 1),
('2025-11-02', 2, 2);

INSERT INTO ITEM_VENDA (ID_PRODUTO, QUANTIDADE_INTEM, PRECO_ITEM, ID_VENDA) VALUES
(1, 2, 3500.00, 1),
(3, 1, 89.90, 1),
(2, 1, 4500.00, 2),
(5, 5, 12.50, 2);

-- VERIFICAÇÃO
SELECT * FROM VENDA;
SELECT * FROM ITEM_VENDA;
SELECT * FROM EMPREGADO;
SELECT * FROM REGISTRADORA;
SELECT * FROM PRODUTO;