-- Usar o schema
USE `mydb`;

-- Limpar tabelas antes (para evitar duplicatas e IDs diferentes)
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE MATRICULA;
TRUNCATE TABLE TURMA;
TRUNCATE TABLE ALUNO;
TRUNCATE TABLE DISCIPLINA;
TRUNCATE TABLE LOCAL;
SET FOREIGN_KEY_CHECKS = 1;

-- 1) TABELA LOCAL
CREATE TABLE IF NOT EXISTS LOCAL (
  COD_LOCAL INT NOT NULL AUTO_INCREMENT,
  NOME_LOCAL VARCHAR(100) NOT NULL,
  PRIMARY KEY (COD_LOCAL)
) ENGINE = InnoDB;

-- 2) TABELA DISCIPLINA
CREATE TABLE IF NOT EXISTS DISCIPLINA (
  COD_DISCIPLINA INT NOT NULL AUTO_INCREMENT,
  NOME_DISCIPLINA VARCHAR(100) NOT NULL,
  PRIMARY KEY (COD_DISCIPLINA)
) ENGINE = InnoDB;

-- 3) TABELA ALUNO
CREATE TABLE IF NOT EXISTS ALUNO (
  COD_ALUNO INT NOT NULL AUTO_INCREMENT,
  NOME_ALUNO VARCHAR(100) NOT NULL,
  LOCAL_COD_LOCAL INT NOT NULL,
  PRIMARY KEY (COD_ALUNO),
  INDEX fk_ALUNO_LOCAL1_idx (LOCAL_COD_LOCAL ASC),
  CONSTRAINT fk_ALUNO_LOCAL1
    FOREIGN KEY (LOCAL_COD_LOCAL)
    REFERENCES LOCAL (COD_LOCAL)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- 4) TABELA TURMA
CREATE TABLE IF NOT EXISTS TURMA (
  COD_TURMA INT NOT NULL AUTO_INCREMENT,
  PERIODO VARCHAR(20) NOT NULL,
  DISCIPLINA_COD_DISCIPLINA INT NOT NULL,
  PRIMARY KEY (COD_TURMA),
  INDEX fk_TURMA_DISCIPLINA1_idx (DISCIPLINA_COD_DISCIPLINA ASC),
  CONSTRAINT fk_TURMA_DISCIPLINA1
    FOREIGN KEY (DISCIPLINA_COD_DISCIPLINA)
    REFERENCES DISCIPLINA (COD_DISCIPLINA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- 5) TABELA MATRÍCULA
CREATE TABLE IF NOT EXISTS MATRICULA (
  ALUNO_COD_ALUNO INT NOT NULL,
  TURMA_COD_TURMA INT NOT NULL,
  ANO_LETIVO YEAR(4) NOT NULL,
  NOTA_FINAL DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (ALUNO_COD_ALUNO, TURMA_COD_TURMA),
  INDEX fk_ALUNO_has_TURMA_TURMA1_idx (TURMA_COD_TURMA ASC),
  INDEX fk_ALUNO_has_TURMA_ALUNO1_idx (ALUNO_COD_ALUNO ASC),
  CONSTRAINT fk_ALUNO_has_TURMA_ALUNO1
    FOREIGN KEY (ALUNO_COD_ALUNO)
    REFERENCES ALUNO (COD_ALUNO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ALUNO_has_TURMA_TURMA1
    FOREIGN KEY (TURMA_COD_TURMA)
    REFERENCES TURMA (COD_TURMA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- =========================
-- INSERINDO DADOS
-- =========================

-- LOCAL
-- LOCAL
INSERT INTO LOCAL (NOME_LOCAL) VALUES
('Franca'),
('Ribeirão Preto'),
('Campinas');

-- DISCIPLINA
INSERT INTO DISCIPLINA (NOME_DISCIPLINA) VALUES
('Matemática'),
('História'),
('Física');

-- ALUNO
INSERT INTO ALUNO (NOME_ALUNO, LOCAL_COD_LOCAL) VALUES
('Roger Silva', 1),
('Ana Costa', 2),
('João Lima', 3);

-- TURMA
INSERT INTO TURMA (PERIODO, DISCIPLINA_COD_DISCIPLINA) VALUES
('2025/1', 1),
('2025/2', 2),
('2026/1', 3);

-- MATRÍCULA
INSERT INTO MATRICULA (ALUNO_COD_ALUNO, TURMA_COD_TURMA, ANO_LETIVO, NOTA_FINAL) VALUES
(1, 1, 2025, 8.5),
(2, 2, 2025, 9.0),
(3, 3, 2026, 7.8),
(1, 2, 2025, 8.0);


SELECT * FROM LOCAL;
SELECT * FROM DISCIPLINA;
SELECT * FROM ALUNO;
SELECT * FROM MATRICULA;

ALTER TABLE ALUNO 
DROP COLUMN COD_LOCAL_NASCIMENTO;






